#!/usr/bin/env python3

"""
Created: 10/08/21
by: Lukas Schüttler

Generate watcherstream configuration
"""

import os
import argparse
import toml

PRESET_PATH = os.path.join(os.path.dirname(
    os.path.abspath(__file__)), 'srtg_preset.toml')
CONFIG_PATH = os.path.join(os.path.dirname(
    os.path.abspath(__file__)), os.pardir, 'srtg.toml')

if __name__ == "__main__":
    print(f"\033[90m{__doc__}\033[0m", end="\n")

    parser = argparse.ArgumentParser()
    parser.add_argument("device_id", help="Name of the Streamer")
    parser.add_argument("token", help="Gametoken")

    args = parser.parse_args()

    config = toml.load(PRESET_PATH)
    config["device_id"] = args.device_id
    config["game_engine"]["token"] = args.token

    with open(CONFIG_PATH, 'w') as f:
        toml.dump(config, f)
